### PR TITLE
Initial implementation of EiOpt service (issue #128 & #70 & #48)

### PR DESCRIPTION
**Pull request by bjohnson75f**
EiOpt service is required for OpenADR 2.0b certification.  We are currently going through the certification process and the certification vendor InterTek requires EiOpt support in order to be certified.

There are 3 issues referring to this particular service: #128 & #70 & #48

This is my first attempt at a basic implementation of this service.

### CODE REVIEW

**Comment by bjohnson75f** [comment]
This PR misses the device assets, so I'm closing it for now.

**Comment by alexcarnero97** [comment]
Hi, I am also interested in passing the OpenADR 2.0b certification for which the EiOpt service needs to be supported. The work and contribution of @bjohnson75f on the library is appreciated but I have some questions: Does the whole implementation work correctly? Does it work to pass the OpenADR 2.0b certification using the EiOpt service? Why did you stop the implementation? Is it intended to merge these changes into the main OpenLEADR branch? Thanks in advance.

**Comment by bjohnson75f** [comment]
Hey @alexcarnero97, I do intend to contribute my work back to this project, however at the time of this PR I realized that I had missed a few pieces in the EiOpt implementation and I am currently struggling with a fairly tight work schedule.  Once I get through the weeds on that effort, I'll circle back to this project and get a PR up that also complies with the contributor guidelines.

As to your other questions, for the pieces that are implemented in OpenLEADR, I believe that they are OpenADR 2.0B compliant, however there is a difference between compliancy and certification.  We have engaged a certification vendor (Intertek) and should actually be beginning that process today or tomorrow, so we'll learn shortly where we fall in that realm.  The EiOpt functionality IS REQUIRED for certification, so while this framework is compliant, it is NOT certifiable as is.  There are other "silly" requirements for certification such as a VEN UI that allows the certification vendor to have a way to cause the VEN to do things such as submit an EiOpt schedule with it's various metadatas.  Even if you do not intend to take advantage of EiOpt, it is still required and is VEN initiated.

I will report back with our findings after we make a little more progress down the road to certification.

**Comment by alexcarnero97** [comment]
All right, thank you very much for everything. I look forward to your results with the certification provider and see what they have to say about the EiOpt service and the other "silly" requirements you mentioned (which I certainly had no idea about). Luckily we are already members of the OpenADR alliance and have the QualityLogic test harness.

**Comment by bjohnson75f** [comment]
Hey @alexcarnero97, what do you think about the QualityLogic test harness?  Have you put it to use and has it been helpful?  Can you tell me what type of platform it runs on and what type of app it is?  e.g. It's a vtn service that runs in a docker container...sort of thing.  Thanks in advance.

**Comment by alexcarnero97** [comment]
Hi @bjohnson75f, yes I have already used it as I am trying to pass the tests to get certified in the future. The test harness is fine, but I am finding that the OpenLEADR library is not quite ready to pass all the tests. It provides basic functionality to implement the OpenADR protocol in Python but it is incomplete as you know, and it is not robust to some of the anomalous scenarios that the test harness raises. The tool consists of a Java project structured in several modules that define different types of services to test, which are compiled and launched.

**Pull request closed without merging**
